spring.application.name=gateway-consumidor-movil

server.port=8084

grpc.client.ms-catalogo.address=static://localhost:9091
grpc.client.ms-catalogo.negotiation-type=plaintext

# --- Rese\u00f1as (Puerto sugerido: 9094) ---
grpc.client.ms-resenias.address=static://localhost:9094
grpc.client.ms-resenias.negotiation-type=plaintext

# --- Multas (Puerto sugerido: 9097) ---
grpc.client.ms-multas.address=static://localhost:9097
grpc.client.ms-multas.negotiation-type=plaintext

# --- Usuarios ---
grpc.client.ms-usuarios.address=static://localhost:9096
grpc.client.ms-usuarios.negotiation-type=plaintext

management.health.grpc.enabled=false
management.metrics.export.simple.enabled=false