spring.application.name=gateway-profeco

server.port=8085

# --- Multas (Puerto sugerido: 9097) ---
grpc.client.ms-multas.address=static://localhost:9097
grpc.client.ms-multas.negotiation-type=plaintext
