    spring.application.name=gateway-comercio
# Puerto HTTP donde tu frontend (React/Angular/Postman) har\u00e1 las peticiones
server.port=8082

# Configuraci\u00f3n del cliente gRPC apuntando a tu microservicio
# "ms-comercio" es el nombre l\u00f3gico que usaremos en el c\u00f3digo
grpc.client.ms-comercio.address=static://localhost:9092
grpc.client.ms-comercio.negotiation-type=plaintext

grpc.client.ms-catalogo.address=static://localhost:9091
grpc.client.ms-catalogo.negotiation-type=plaintext

# --- Rese\u00f1as (Puerto sugerido: 9094) ---
grpc.client.ms-resenias.address=static://localhost:9094
grpc.client.ms-resenias.negotiation-type=plaintext

# --- Ofertas (Puerto sugerido: 9095) ---
grpc.client.ms-ofertas.address=static://localhost:9095
grpc.client.ms-ofertas.negotiation-type=plaintext

# --- Usuarios ---
grpc.client.ms-usuarios.address=static://localhost:9096
grpc.client.ms-usuarios.negotiation-type=plaintext

management.health.grpc.enabled=false
management.metrics.export.simple.enabled=false