CREATE DATABASE IF NOT EXISTS catalogo_db;
CREATE DATABASE IF NOT EXISTS comercio_db;
CREATE DATABASE IF NOT EXISTS multas_db;
CREATE DATABASE IF NOT EXISTS ofertas_db;
CREATE DATABASE IF NOT EXISTS resenias_db;
CREATE DATABASE IF NOT EXISTS usuarios_db;